/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.sardine.prototob1;

import org.junit.Test;
import static org.junit.Assert.*;

public class ProtoToBigQueryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
